//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.08 at 10:37:47 AM CEST 
//


package parser.model;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import parser.model.abs.DocumentAbs;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BkToCstmrStmt" type="{urn:iso:std:iso:20022:tech:xsd:camt.052.001.02}BankToCustomerStatementV02"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="Document")
@XmlType(name = "Document", propOrder = {
    "bkToCstmrAcctRpt"
})
public class Document052 extends DocumentAbs {

    @XmlElement(name = "BkToCstmrAcctRpt", required = true)
    protected  BankToCustomerAccountReportV02 bkToCstmrAcctRpt;

	/**
	 * @return the bkToCstmrAcctRpt
	 */
	public BankToCustomerAccountReportV02 getBkToCstmrAcctRpt()
	{
		return bkToCstmrAcctRpt;
	}

	/**
	 * @param bkToCstmrAcctRpt the bkToCstmrAcctRpt to set
	 */
	public void setBkToCstmrAcctRpt(BankToCustomerAccountReportV02 bkToCstmrAcctRpt)
	{
		this.bkToCstmrAcctRpt = bkToCstmrAcctRpt;
	}



}
